services:
  postgres:
    image: postgres:18
    container_name: hyvor-relay-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?postgres password not set}
      POSTGRES_DB: hyvor_relay
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hyvor_relay"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      # Since the app runs in host network mode, we bind Postgres to the host
      # 127.0.0.1 makes it accessible only locally.
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  relay:
    image: hyvor/relay:latest
    container_name: hyvor-relay
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: "host"
    env_file:
      - .env
    # 国内服务访问国外DNS验证的如果有问题，需要添加代理
    environment:
      - HTTPS_PROXY=http://127.0.0.1:7890
      - HTTP_PROXY=http://127.0.0.1:7890
      - GO_SYMFONY_URL=http://localhost:8080
    # 添加caddy单独配置，不影响服务器默认caddy配置
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile

volumes:
  postgres_data:
